task_seq:
    - R1_SLAM
    - R2_Navigation
    - R2_Obj_Detection
    - R1_Navigation
    - R1_Obj_Detection
    - R2_SLAM
    - R3_SLAM
    - R3_Navigation
    - R3_Obj_Detection
    - Map_Merging

task_req: { 
  'R1_SLAM' : [34, 36, 37], 
  'R1_Navigation': [64, 65, 66],
  'R1_Obj_Detection': [70, 71, 72], 
  'Map_Merging': [90, 91, 92],
  'R2_SLAM' : [24, 26, 27], 
  'R2_Navigation': [14, 35, 16],
  'R2_Obj_Detection': [50, 51, 52], 
  'R3_SLAM' : [44, 46, 47], 
  'R3_Navigation': [64, 65, 66],
  'R3_Obj_Detection': [90, 91, 92]
}

# Without post-conditions
task_req_seq: {
  'R1_SLAM' : ['R1_SLAM'], 
  'R1_Navigation': ['R1_SLAM','R1_Navigation'],
  'R1_Obj_Detection': ['R1_Obj_Detection'], 
  'Map_Merging': ['R1_SLAM','R2_SLAM','R3_SLAM','Map_Merging'],
  'R2_SLAM' : ['R2_SLAM'],
  'R2_Navigation': ['R2_SLAM','R2_Navigation'],
  'R2_Obj_Detection': ['R1_Obj_Detection'], 
  'R3_SLAM' : ['R3_SLAM'],
  'R3_Navigation': ['R3_SLAM','R3_Navigation'],
  'R3_Obj_Detection': ['R3_Obj_Detection']
}

weights: {
  'CPU' : [1, 0, 0, 0],
  'Memory' : [0, 1, 0, 0],
  'Network': [0, 0, 1, 0],
  'Nodes': [0, 0, 0, 1]
}


